/**
 * JewelForge v2 — PBR material presets (JavaScript/Three.js version).
 * Mirrors backend/materials/presets.py.
 * Color values are hex numbers compatible with new THREE.Color(value).
 */

export const METAL_PRESETS = {
  yellow_gold: {
    name: 'Yellow Gold (18K)',
    color: 0xFFD700,
    metalness: 1.0,
    roughness: 0.15,
    envMapIntensity: 1.2,
    pricePerGram: 62.50,
  },
  white_gold: {
    name: 'White Gold (18K)',
    color: 0xE8E8E8,
    metalness: 1.0,
    roughness: 0.12,
    envMapIntensity: 1.3,
    pricePerGram: 65.00,
  },
  rose_gold: {
    name: 'Rose Gold (18K)',
    color: 0xE8956D,
    metalness: 1.0,
    roughness: 0.15,
    envMapIntensity: 1.2,
    pricePerGram: 60.00,
  },
  platinum: {
    name: 'Platinum (950)',
    color: 0xD4D4D4,
    metalness: 1.0,
    roughness: 0.08,
    envMapIntensity: 1.4,
    pricePerGram: 32.00,
  },
  silver: {
    name: 'Sterling Silver (925)',
    color: 0xC0C0C0,
    metalness: 1.0,
    roughness: 0.20,
    envMapIntensity: 1.0,
    pricePerGram: 0.85,
  },
  copper: {
    name: 'Copper',
    color: 0xB87333,
    metalness: 1.0,
    roughness: 0.35,
    envMapIntensity: 0.9,
    pricePerGram: 0.01,
  },
}

export const GEMSTONE_PRESETS = {
  diamond: {
    name: 'Diamond',
    color: 0xF5F5FF,
    metalness: 0.0,
    roughness: 0.0,
    transmission: 0.95,
    ior: 2.42,
    thickness: 0.5,
    envMapIntensity: 2.0,
    pricePerCarat: 5000.00,
  },
  ruby: {
    name: 'Ruby',
    color: 0xCC0022,
    metalness: 0.0,
    roughness: 0.05,
    transmission: 0.6,
    ior: 1.77,
    thickness: 0.5,
    envMapIntensity: 1.6,
    pricePerCarat: 3000.00,
  },
  sapphire: {
    name: 'Sapphire',
    color: 0x0044CC,
    metalness: 0.0,
    roughness: 0.05,
    transmission: 0.65,
    ior: 1.77,
    thickness: 0.5,
    envMapIntensity: 1.6,
    pricePerCarat: 2500.00,
  },
  emerald: {
    name: 'Emerald',
    color: 0x006622,
    metalness: 0.0,
    roughness: 0.08,
    transmission: 0.5,
    ior: 1.58,
    thickness: 0.5,
    envMapIntensity: 1.5,
    pricePerCarat: 4000.00,
  },
  amethyst: {
    name: 'Amethyst',
    color: 0x8B44CC,
    metalness: 0.0,
    roughness: 0.05,
    transmission: 0.7,
    ior: 1.54,
    thickness: 0.4,
    envMapIntensity: 1.4,
    pricePerCarat: 20.00,
  },
  topaz: {
    name: 'Topaz',
    color: 0xFFC050,
    metalness: 0.0,
    roughness: 0.04,
    transmission: 0.75,
    ior: 1.62,
    thickness: 0.4,
    envMapIntensity: 1.5,
    pricePerCarat: 25.00,
  },
  cubic_zirconia: {
    name: 'Cubic Zirconia',
    color: 0xF8F8FF,
    metalness: 0.0,
    roughness: 0.02,
    transmission: 0.9,
    ior: 2.15,
    thickness: 0.4,
    envMapIntensity: 1.8,
    pricePerCarat: 2.00,
  },
}
